version: '3.8'

services:
  web:
    build: ./services/web
    volumes:
      - ./services/web/:/usr/src/app/
    ports:
      - 8000:8000
    env_file:
      - ./.env.dev
    depends_on:
      - db
  db:
    image: postgres:13-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=verbaquiz
      - POSTGRES_PASSWORD=verbaquiz
      - POSTGRES_DB=verbaquiz_dev
    ports:
      - "6543:5432"

volumes:
  postgres_data:
